### ISSUE TITLE
phase_name for all Event ID's is not being captured by Sentinel

### ISSUE THREAD

**Issue by edoardogerosa** [BlueTeamToolkit/sentinel-attack#17]
I have followed your guides, however phase_name is not being captured in Sentinel:

![No-Phase_Name](https://user-images.githubusercontent.com/10306855/65034388-dd915600-d93e-11e9-8716-43df1264efeb.PNG)

However the parser was installed successfully:

![PArser-EventID5-Phase_Name](https://user-images.githubusercontent.com/10306855/65030999-6789f080-d938-11e9-9de6-c88956923f78.PNG)

And I can clearly see the phase_name in the sysmon event on the server:

![Sysmon-EventID5](https://user-images.githubusercontent.com/10306855/65031109-8f795400-d938-11e9-9154-f77d8856eb57.PNG)

So I'm a little lost. Also, when querying the log, the column names do not seem to correspond with the data they contain, which suggests perhaps an issue with the parser (?):

![Parser-Columns Data](https://user-images.githubusercontent.com/10306855/65033142-5b079700-d93c-11e9-9392-95368cb9ab2c.PNG)

_Originally posted by @srthomson in https://github.com/BlueTeamLabs/sentinel-attack/issues/15#issuecomment-532157466_

**Comment by CyberSecOps** [comment]
Unfortunately it's not being captured in any if the EventID's, the issue is not isolated to just EventID 5.

**Comment by edoardogerosa** [comment]
Hi @srthomson , i'm struggling to replicate the behaviour you are describing. I have run a couple of tests on a Win10 machine using the latest version of Sysmon (v10.4), the parser contaning latest fixes and the sysmonconfig.xml from our repository. In all cases where sysmon captures RuleName information this is picked up by Sentinel and phase_name is correctly parsed by the Sysmon-OSSEM parser. For reference I attach a screenshot of a test command i ran:
![image](https://user-images.githubusercontent.com/36902303/65081797-c1280480-d9a4-11e9-8215-1997ce6a74e2.png)

And the related log picked up and correctly parsed within Sentinel:
![image](https://user-images.githubusercontent.com/36902303/65081930-051b0980-d9a5-11e9-8221-89083ab10a09.png)

Maybe i'm missing something; in order to better help i suggest you reinstall the latest Sysmon-OSSEM parser in Sentinel and re-run some tests. Keep in mind that it might take a couple minutes for the parser to become effective within Sentinel. Once you've done that please let me know the exact steps you performed, with an accurate description of the environment used, and i'll do my best to replicate.

On a sidenote i've noticed errors in the parsing of Event ID 1; i've opened issue #18 to address this bug later on.

**Comment by CyberSecOps** [comment]
Re-installing the latest parser fixed the issue. Thank you.
