### ISSUE TITLE
Parser/Sysmon missing MITRE attribution details for EventID 22

### ISSUE THREAD

**Issue by CyberSecOps** [BlueTeamToolkit/sentinel-attack#19]
![Parser-EventID-22](https://user-images.githubusercontent.com/10306855/65145081-98d5ef80-da10-11e9-9df2-23f260515ea3.PNG)

There's no technique_id, technique_name or phase_name attributed in Sysmon EventID 22.

**Comment by edoardogerosa** [comment]
In the current sysmonconfig.xml we only have exclusion rules for Sysmon EventID 22 defined at the moment; there is definitely scope to insert inclusion rules mapped to MITRE ATT&CK. Looping in @olafhartong for visibility.
