### ISSUE TITLE
cost related to doing the sentinel attack ?

### ISSUE THREAD

**Issue by ssi0202** [BlueTeamToolkit/sentinel-attack#20]
hi is there anywhere i can get input as to caculating what cost a setup like what you have build here for approx 100 servers

i have run sysmon and can see that my servers individually generate an approx abount of data pr day. This is easy to multiply and I can also look at the cost calculator in terms of GB sent to sentinel.

But what about the ksql queries, will i not get additional cost if i set these to run at 5,10,15 min interval, and will this cost not go up as I apply more of the ksql queries ?

**Comment by edoardogerosa** [comment]
Added costs paragraph on wiki home page
