### ISSUE TITLE
Parse config

### ISSUE THREAD

**Issue by akapv** [BlueTeamToolkit/sentinel-attack#40]
Hi!
just to let you know that on SysmonEvent13 section seems to have a double __ on the name:

let SysmonEvent13__RegistrySetValue=() {

Congrats for this brilliant project

**Comment by edoardogerosa** [comment]
Thank you @akapv for pointing this issue out - hugely appreciate it. In the future, should you want to, feel free to directly make a pull request; they are most welcome 😃
