### ISSUE TITLE
Incorrect logic in "T1093_Process_Holoowing.txt" KQL 

### ISSUE THREAD

**Issue by spwn3d1** [BlueTeamToolkit/sentinel-attack#45]
Hello, 

The logic searches for several key processes in the process_path attribute and then searches the process_parent_command_line.  **Within this second filter it is incorrectly using an OR statement instead of another AND since both checks are !contains they should both be true.**  The OR statement will generate false positives as both can legitimately call the userinit.exe process in this particular example and only one needs to be satisfied as non-existent.  This logic issue exists in all of the subprocesses.
or (process_path contains "userinit.exe"
and (process_parent_command_line !contains "dwm.exe" **or** process_parent_command_line !contains "winlogon.exe"))

Solution:
I propose you update the '**or**' to an '**and**' between each of the process_parent_command_line !contains statements.  

Also, minor tweak the name of this KQL has a spelling issue in 'hollowing.'

**Comment by edoardogerosa** [comment]
Thank you for your submission @spwn3d1 - the logic has been fixed with #47
