### ISSUE TITLE
Missing page/bad link

### ISSUE THREAD

**Issue by rod-trent** [BlueTeamToolkit/sentinel-attack#46]
From the "Configuring whitelisting functions and understanding how to use them" page, the following link is not found:  https://github.com/BlueTeamLabs/sentinel-attack/tree/master/hunting/functions

The whitelisting functions are located in the _**hunting/functions**_ folder and are distributed as .txt files. Each file contains a whitelisting function. To install the whitelisting functions you must:

**Comment by homa1978** [comment]
any updates on this where can i found the functions files ?

**Comment by edoardogerosa** [comment]
Hi @rod-trent and @homa1978  - many thanks for your submission. The bad link and _configure whitelisting functions_ section of the wiki have been removed as they were redundant. The whitelisting functions are automatically provisioned within the sysmon threat hunting workbook.
